config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  get 'sign_in', to: 'sessions#new', as: :sign_in
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out

  resources :employees, only: :index
  resources :orders, only: :show do
    resource :fulfill, only: [:create]
  end

  resources :products do
    resource :receive, only: [:create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates :recipient, :street_1, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :access_code, uniqueness: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  enum status: InventoryStatusChange::STATUSES
  belongs_to :product
  belongs_to :order, required: false

  validates :product, presence: true
end

app/models/inventory_status_change.rb
class InventoryStatusChange < ApplicationRecord
  STATUSES = {
    on_shelf: 'on_shelf',
    shipped: 'shipped'
  }.freeze

  belongs_to :inventory
  belongs_to :actor, class_name: 'Employee'

  enum status_from: STATUSES, _prefix: :from
  enum status_to: STATUSES, _prefix: :to

  validates :status_to, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :ships_to, class_name: 'Address'
  has_many :line_items, class_name: 'OrderLineItem'
  has_many :inventories

  scope :recent, -> { order(created_at: :desc) }
  scope :fulfilled, -> { joins(:inventories).group('orders.id') }
  scope :not_fulfilled, -> { left_joins(:inventories).where(inventories: { order_id: nil }) }
  scope :fulfillable, lambda {
    not_fulfilled
      .joins(:line_items)
      .joins(<<~SQL)
        LEFT OUTER JOIN product_on_shelf_quantities
          ON order_line_items.product_id = product_on_shelf_quantities.product_id
         AND order_line_items.quantity <= product_on_shelf_quantities.quantity
      SQL
      .group(:id)
      .having(<<~SQL)
        COUNT(DISTINCT product_on_shelf_quantities.product_id) =
        COUNT(DISTINCT order_line_items.product_id)
      SQL
      .order(:created_at, :id)
  }

  def cost
    line_items.inject(Money.zero) do |acc, li|
      acc + li.cost
    end
  end

  def fulfilled?
    inventories.any?
  end

  def fulfillable?
    line_items.all?(&:fulfillable?)
  end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, numericality: { greater_than: 0 }

  def cost
    quantity * product.price
  end

  def on_shelf_quantity
    ProductOnShelfQuantity.find_by(product:)&.quantity || 0
  end

  def fulfillable?
    on_shelf_quantity >= quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  monetize :price_cents
  has_many :inventory

  def in_stock_count
    inventory.on_shelf.count
  end

  def needed_inventory_count
    self.class.connection.select_value(<<~SQL)
      SELECT GREATEST(
        SUM(order_line_items.quantity) - (
          SELECT quantity FROM product_on_shelf_quantities WHERE product_id = #{id}
        ), 0)
      FROM order_line_items
        LEFT OUTER JOIN inventories
          ON order_line_items.order_id = inventories.order_id
      WHERE order_line_items.product_id = #{id}
        AND inventories.order_id IS NULL
    SQL
  end
end

app/models/product_on_shelf_quantity.rb
class ProductOnShelfQuantity < ApplicationRecord
  belongs_to :product

  def readonly?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    if session[:employee_id]
      Employee.find_by(id: session[:employee_id])
    end
  end

  helper_method :current_user

  def signed_in?
    current_user.present?
  end

  helper_method :signed_in?

  def require_signin
    if signed_out?
      redirect_to sign_in_path
    end
  end

  def sign_in_as(employee)
    session[:employee_id] = employee.id
  end

  def sign_out
    session[:employee_id] = nil
  end

  def signed_out?
    !signed_in?
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_signin

  def index
    @fulfillable_orders = Order.fulfillable.limit(10)
    @recent_orders = Order.recent.limit(10)
    @products = Product.all
  end
end

app/controllers/fulfills_controller.rb
class FulfillsController < ApplicationController
  def create
    FindFulfillableOrder.fulfill_order(current_user, params[:order_id])

    redirect_to employees_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_signin

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:inventory).order(id: :asc)
  end
end

app/controllers/receives_controller.rb
class ReceivesController < ApplicationController
  before_action :require_signin

  def create
    ReceiveProduct.run(current_user, product, product_quantity)
    redirect_to employees_path
  end

  private

  def product
    Product.find(params[:product_id])
  end

  def product_quantity
    Integer(params.require(:receive_product).permit(:quantity)[:quantity])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    employee = Employee.find_by(access_code: access_code_param[:access_code])

    if employee
      sign_in_as(employee)
      redirect_to employees_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  def access_code_param
    params.require(:session).permit(:access_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def employee_breadcrumb(&block)
    content_tag 'ul', class: 'employees__header flex text-gray-600 py-4 text-2xl font-semibold' do
      base = content_tag 'li', nil, class: 'text-teal-700' do
        link_to t('employees.index.title'), employees_path, class: 'underline'
      end

      concat(base)

      if block_given?
        concat content_tag('li', '/', class: 'mx-2')
        concat content_tag('li', capture { block.call(self) })
      end
    end
  end

  def order_status(order)
    if order.fulfilled?
      t('order.fulfilled')
    elsif order.fulfillable?
      t('order.fulfillable')
    else
      t('order.unfulfillable')
    end
  end

  def order_status_class(order)
    if order.fulfilled?
      'bg-green-200 text-green-800'
    elsif order.fulfillable?
      'bg-yellow-200 text-yellow-800'
    else
      'bg-red-200 text-red-800'
    end
  end

  def line_item_fulfillable_class(order, line_item)
    if !order.fulfilled?
      if line_item.fulfillable?
        'bg-green-100 text-green-800'
      else
        'bg-red-100 text-red-800'
      end
    end
  end

  def fulfill_order_button_class(order)
    if order.fulfillable?
      'bg-teal-600 text-white'
    else
      'bg-gray-500 text-gray-300 cursor-not-allowed'
    end
  end
end

app/views/employees/index.html.erb
<%= employee_breadcrumb %>

<p class='employees__welcome text-xl font-light pb-4'><%= t '.welcome', name: current_user.name %></p>

<div class='flex flex-wrap md:-mx-2 lg:-mx-2'>
  <div class='mb-4 md:px-2 lg:px-2 w-full md:w-1/2 lg:w-1/2'>
    <div class='bg-white rounded-md shadow-md border overflow-hidden'>
      <h3 class='text-2xl font-bold px-4 py-2'><%= t '.receive_product.header' %></h3>
      <table class='generic-table zebra'>
        <thead>
          <tr>
            <th><%= t '.receive_product.table.product' %></th>
            <th class='number'><%= t '.receive_product.table.quantity' %></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr data-id='product-<%= product.id %>'>
              <td>
                <%= product.name %>
                <div class='metadata'>
                  <%= t '.receive_product.table.on_shelf', count: product.in_stock_count %>
                </div>
                <div class='metadata'>
                  <%= t '.receive_product.table.needed', count: product.needed_inventory_count %>
                </div>
              </td>
              <td class='number'>
                <%= form_for :receive_product, url: product_receive_path(product) do |form| %>
                  <%= form.label :quantity, class: 'hidden' %>
                  <%= form.number_field :quantity, min: 1, required: true, class: 'w-24 border p-1 text-right rounded-sm' %>
                  <%= form.submit class: 'bg-teal-600 text-white p-1 px-3 ml-2' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% if @fulfillable_orders.any? %>
    <div class='mb-4 md:px-2 lg:px-2 w-full md:w-1/2 lg:w-1/2'>
      <div class='bg-white rounded-md shadow-md border overflow-hidden'>
        <h3 class='text-2xl font-bold px-4 py-2'><%= t '.fulfillable_orders.header' %></h3>
        <%= render 'orders/table', orders: @fulfillable_orders %>
      </div>
    </div>
  <% end %>
  <div class='mb-4 md:px-2 lg:px-2 w-full md:w-1/2 lg:w-1/2'>
    <div class='bg-white rounded-md shadow-md border overflow-hidden'>
      <h3 class='text-2xl font-bold px-4 py-2'><%= t '.recent_orders.header' %></h3>
      <%= render 'orders/table', orders: @recent_orders %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='h-full'>
  <head>
    <title><%= t '.page_title' %></title>
    <meta charset='utf-8' />
    <meta http-equiv='x-ua-compatible' content='ie=edge' />
    <meta
      name='viewport'
      content='width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1'
    />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-gray-100 text-gray-800'>
    <div class='min-h-screen lg:mx-auto lg:container'>
      <div class='flex justify-between items-center'>
        <header class='text-4xl font-bold px-8 py-4'>
          <%= link_to root_path do %>
            <h1><%= t ".page_title" %></h1>
          <% end %>
        </header>
        <div class='px-8'>
          <% if controller_name != 'sessions' %>
            <% if signed_in? %>
              <%= link_to t(".portal"), employees_path, class: 'mr-2' %>
              <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
            <% else %>
              <%= link_to t(".sign_in"), sign_in_path %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class='px-8'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/orders/_table.html.erb
<table class='generic-table zebra'>
  <thead>
    <tr>
      <th><%= t '.fulfilled' %></th>
      <th><%= t '.order_id' %></th>
      <th class='number'><%= t '.order_amount' %></th>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |order| %>
      <tr data-id='order-<%= order.id %>'>
        <td>
          <span class='px-2 py-1 rounded-md text-xs shadow-sm <%= order_status_class(order) %>'>
            <%= order_status(order) %>
          </span>
        </td>
        <td>
          <div>
            <%= link_to order_path(order) do %>
              <%= t '.order_id_value', id: order.id %>
            <% end %>
          </div>
          <div class='text-xs text-gray-400'>
            <%= order.ships_to.recipient %>
          </div>
        </td>
        <td class='number'>
          <div>
            <%= humanized_money_with_symbol order.cost %>
          </div>
          <div class='metadata'>
            <%= t '.product_count', count: order.line_items.sum(:quantity) %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<%= employee_breadcrumb do %>
  <%= t '.order.header', id: @order.id %>
<% end %>

<div class='flex flex-wrap'>
  <% if @order.fulfilled? %>
    <div class='w-full text-center p-4 shadow-sm mb-4 text-xl bg-green-200 rounded-md font-semibold text-green-800'>
      <%= t '.order.fulfilled' %>
    </div>
  <% end %>
  <div class='md:w-1/3'>
    <h3 class='text-2xl font-semibold pb-4'><%= t '.ships_to.header' %></h3>
    <div>
      <p><%= @order.ships_to.recipient %></p>
      <p><%= @order.ships_to.street_1 %></p>
      <p><%= @order.ships_to.street_2 %></p>
      <p><%= @order.ships_to.city %>, <%= @order.ships_to.state %> <%= @order.ships_to.zip %></p>
    </div>
  </div>

  <div class='md:w-2/3 w-full bg-white rounded-md shadow-md border overflow-hidden'>
    <h3 class='text-2xl font-semibold p-4'><%= t '.products.header' %></h3>
    <div>
      <table class='generic-table zebra'>
        <thead>
          <tr>
            <th class='number'><%= t '.product_table.thead.quantity' %></th>
            <th><%= t '.product_table.thead.name' %></th>
            <th class='number'><%= t '.product_table.thead.cost' %></th>
          </tr>
        </thead>
        <tbody>
          <% @order.line_items.each do |line_item| %>
            <tr>
              <td class='number <%= line_item_fulfillable_class(@order, line_item) %>'>
                <div>
                  <%= line_item.quantity %>
                </div>
                <% if !@order.fulfilled? %>
                  <div class='text-xs italic'>
                    <%= t '.product_table.on_shelf', count: line_item.on_shelf_quantity %>
                  </div>
                <% end %>
              </td>
              <td><%= line_item.product.name %></td>
              <td class='number'><%= humanized_money_with_symbol line_item.cost %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th class='number' colspan='2'><%= t '.product_table.order_total' %></th>
            <td class='number'><%= humanized_money_with_symbol @order.cost %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <% if !@order.fulfilled? %>
      <%= button_to order_fulfill_path(@order), method: :post, class: "w-full p-4 text-2xl #{fulfill_order_button_class(@order)}", disabled: !@order.fulfillable? do %>
        <%= t '.fulfill_order' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<h2 class='text-2xl py-4 text-teal-700 font-semibold'><%= t '.title' %></h2>

<div class='flex flex-wrap mb-4 -mx-1 lg:-mx-4'>
  <% @products.each do |product| %>
    <div data-id='product-<%= product.id %>' class='my-2 px-2 w-full md:w-1/2 md:my-3 md:px-3 lg:my-4 lg:px-4 lg:w-1/3'>
      <div class='product bg-white rounded-md shadow-md overflow-hidden'>
        <img src='https://via.placeholder.com/450x250' class='object-cover w-full' />
        <div class='p-4'>
          <div class='flex justify-between items-center pb-1'>
            <h3 class='product__header font-semibold'><%= product.name %></h3>
            <p class='product__price'><%= humanized_money_with_symbol product.price %></p>
          </div>
          <div class='product__quantity text-gray-400 text-xs italic'><%= t ".quantity", count: product.in_stock_count %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>